development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:6f87a78dde74e60c6aaa99655ba1815c@barb.redistogo.com:10267/
  channel_prefix: rails-chatapp-actioncable_production
